server:
  port: 8088
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql:///practice_system?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: cvte1234
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 1000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 2000ms


mybatis-plus:
  mapper-locations: classpath:mapper.*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.practice.entiry
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      db-type: mysql
    #刷新mapper 调试神器,开发时打开
    refresh: true
  # 原生配置
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true

unLoginApi: /member/login